### ISSUE TITLE
Call to undefined method Parsedown::text()

### ISSUE THREAD

**Issue by skerbis** [FriendsOfREDAXO/pdfout#5]
Redaxo 5.2

> "Error" thrown in /var/www/vhosts/new.wv-n.de/httpdocs/redaxo/src/addons/pdfout/pages/main.php on line 4
> Call to undefined method Parsedown::text()
> 
> #0 /var/www/vhosts/new.wv-n.de/httpdocs/redaxo/src/addons/pdfout/pages/index.php(16): include()
> #1 /var/www/vhosts/new.wv-n.de/httpdocs/redaxo/src/core/lib/packages/package.php(228): include('/var/www/vhosts...')
> #2 /var/www/vhosts/new.wv-n.de/httpdocs/redaxo/src/core/lib/be/controller.php(456): rex_package->includeFile('pages/index.php', Array)
> #3 /var/www/vhosts/new.wv-n.de/httpdocs/redaxo/src/core/lib/be/controller.php(403): rex_be_controller::includePath('/var/www/vhosts...')
> #4 /var/www/vhosts/new.wv-n.de/httpdocs/redaxo/src/core/backend.php(138): rex_be_controller::includeCurrentPage()
> #5 /var/www/vhosts/new.wv-n.de/httpdocs/redaxo/src/core/boot.php(105): require('/var/www/vhosts...')
> #6 /var/www/vhosts/new.wv-n.de/httpdocs/redaxo/index.php(9): require('/var/www/vhosts...')
> #7 {main}

**Comment by skerbis** [comment]
Schuld war das Addon: customelements
